"""ride requests events and alerts

Revision ID: 8c89b43d6230
Revises: c2b7ff33e90f
Create Date: 2026-09-24 22:01:56.892631

"""

from collections.abc import Sequence

import geoalchemy2  # noqa: F401  (geography columns render as geoalchemy2.types.*)
import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8c89b43d6230"
down_revision: str | Sequence[str] | None = "c2b7ff33e90f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ride_request",
        sa.Column("client_id", sa.UUID(), nullable=False),
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column(
            "direction",
            sa.Enum("to_office", "from_office", name="direction", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("office_id", sa.UUID(), nullable=False),
        sa.Column(
            "location",
            geoalchemy2.types.Geography(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeogFromText",
                name="geography",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("landmark", sa.String(length=200), nullable=True),
        sa.Column("requested_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "urgency",
            sa.Enum("high", "medium", "low", name="urgency", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("no_sharing", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "requested",
                "queued",
                "suggested",
                "assigned",
                "picked_up",
                "dropped",
                "no_show",
                "cancelled",
                "expired",
                name="requeststatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "channel",
            sa.Enum(
                "app",
                "supervisor",
                "offer",
                "sim",
                name="requestchannel",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column("trip_id", sa.UUID(), nullable=True),
        sa.Column("lock_vehicle_id", sa.UUID(), nullable=True),
        sa.Column("forced_priority", sa.Boolean(), nullable=False),
        sa.Column("hold_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("override_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_reason", sa.String(length=200), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("near_expiry_alerted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("operator_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["client_id"], ["client.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["app_user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["employee_id"], ["employee.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["lock_vehicle_id"], ["vehicle.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["office_id"], ["office.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["operator_id"], ["operator.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_ride_request_employee_time",
        "ride_request",
        ["employee_id", "requested_time"],
        unique=False,
    )
    op.create_index(
        "ix_ride_request_open",
        "ride_request",
        ["operator_id", "status", "requested_time"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ride_request_operator_id"), "ride_request", ["operator_id"], unique=False
    )
    op.create_index(
        "ix_ride_request_operator_status", "ride_request", ["operator_id", "status"], unique=False
    )
    op.create_table(
        "alert",
        sa.Column(
            "type",
            sa.Enum(
                "sos",
                "driver_issue",
                "request_near_expiry",
                "vip_no_vehicle",
                "failsafe",
                "stale_vehicle",
                "mode_prompt",
                "system",
                name="alerttype",
                native_enum=False,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column(
            "severity",
            sa.Enum(
                "info", "warning", "critical", name="alertseverity", native_enum=False, length=20
            ),
            nullable=False,
        ),
        sa.Column("request_id", sa.UUID(), nullable=True),
        sa.Column("trip_id", sa.UUID(), nullable=True),
        sa.Column("vehicle_id", sa.UUID(), nullable=True),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "open", "acknowledged", "resolved", name="alertstatus", native_enum=False, length=20
            ),
            nullable=False,
        ),
        sa.Column("acknowledged_by", sa.UUID(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("operator_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["acknowledged_by"], ["app_user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["operator_id"], ["operator.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["request_id"], ["ride_request.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["vehicle_id"], ["vehicle.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_alert_operator_id"), "alert", ["operator_id"], unique=False)
    op.create_index("ix_alert_operator_status", "alert", ["operator_id", "status"], unique=False)
    op.create_index("ix_alert_request", "alert", ["request_id"], unique=False)
    op.create_table(
        "ride_request_event",
        sa.Column("request_id", sa.UUID(), nullable=False),
        sa.Column("from_status", sa.String(length=20), nullable=True),
        sa.Column("to_status", sa.String(length=20), nullable=False),
        sa.Column(
            "actor_type",
            sa.Enum(
                "employee",
                "driver",
                "supervisor",
                "system",
                "system_failsafe",
                "optimizer",
                name="actortype",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("reason", sa.String(length=200), nullable=True),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("operator_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["actor_user_id"], ["app_user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["operator_id"], ["operator.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["request_id"], ["ride_request.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ride_request_event_operator_id"),
        "ride_request_event",
        ["operator_id"],
        unique=False,
    )
    op.create_index(
        "ix_ride_request_event_request", "ride_request_event", ["request_id", "at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_ride_request_event_request", table_name="ride_request_event")
    op.drop_index(op.f("ix_ride_request_event_operator_id"), table_name="ride_request_event")
    op.drop_table("ride_request_event")
    op.drop_index("ix_alert_request", table_name="alert")
    op.drop_index("ix_alert_operator_status", table_name="alert")
    op.drop_index(op.f("ix_alert_operator_id"), table_name="alert")
    op.drop_table("alert")
    op.drop_index("ix_ride_request_operator_status", table_name="ride_request")
    op.drop_index(op.f("ix_ride_request_operator_id"), table_name="ride_request")
    op.drop_index("ix_ride_request_open", table_name="ride_request")
    op.drop_index("ix_ride_request_employee_time", table_name="ride_request")
    op.drop_table("ride_request")
    # ### end Alembic commands ###
