"""trip, trip_stop, trip_event

Revision ID: 8e3b6bba35be
Revises: 0176544eef99
Create Date: 2026-09-25 09:24:43.257656

"""

from collections.abc import Sequence

import geoalchemy2  # noqa: F401  (geography columns render as geoalchemy2.types.*)
import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8e3b6bba35be"
down_revision: str | Sequence[str] | None = "0176544eef99"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trip",
        sa.Column("vehicle_id", sa.UUID(), nullable=False),
        sa.Column("driver_id", sa.UUID(), nullable=False),
        sa.Column(
            "direction",
            sa.Enum("to_office", "from_office", name="direction", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("office_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "planned",
                "dispatched",
                "in_progress",
                "completed",
                "cancelled",
                "aborted",
                name="tripstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("pooling_blocked", sa.Boolean(), nullable=False),
        sa.Column("planned_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("planned_distance_m", sa.Float(), nullable=True),
        sa.Column("actual_distance_m", sa.Float(), nullable=True),
        sa.Column("empty_distance_m", sa.Float(), nullable=True),
        sa.Column("mode_used", sa.String(length=20), nullable=False),
        sa.Column(
            "route_geometry",
            geoalchemy2.types.Geography(
                geometry_type="LINESTRING",
                srid=4326,
                dimension=2,
                from_text="ST_GeogFromText",
                name="geography",
            ),
            nullable=True,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("operator_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["driver_id"], ["driver.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["office_id"], ["office.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["operator_id"], ["operator.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["vehicle_id"], ["vehicle.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_trip_operator_id"), "trip", ["operator_id"], unique=False)
    op.create_index("ix_trip_operator_status", "trip", ["operator_id", "status"], unique=False)
    op.create_index("ix_trip_vehicle_status", "trip", ["vehicle_id", "status"], unique=False)
    op.create_table(
        "trip_event",
        sa.Column("trip_id", sa.UUID(), nullable=False),
        sa.Column("from_status", sa.String(length=20), nullable=True),
        sa.Column("to_status", sa.String(length=20), nullable=False),
        sa.Column(
            "actor_type",
            sa.Enum(
                "employee",
                "driver",
                "supervisor",
                "system",
                "system_failsafe",
                "optimizer",
                name="actortype",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("reason", sa.String(length=200), nullable=True),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("operator_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["actor_user_id"], ["app_user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["operator_id"], ["operator.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["trip_id"], ["trip.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_trip_event_operator_id"), "trip_event", ["operator_id"], unique=False)
    op.create_index("ix_trip_event_trip", "trip_event", ["trip_id", "at"], unique=False)
    op.create_table(
        "trip_stop",
        sa.Column("trip_id", sa.UUID(), nullable=False),
        sa.Column("sequence", sa.SmallInteger(), nullable=False),
        sa.Column(
            "stop_type",
            sa.Enum("pickup", "drop", name="stopkind", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("request_id", sa.UUID(), nullable=False),
        sa.Column(
            "location",
            geoalchemy2.types.Geography(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeogFromText",
                name="geography",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "en_route",
                "arrived",
                "done",
                "skipped",
                name="stopstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("planned_eta", sa.DateTime(timezone=True), nullable=True),
        sa.Column("latest_eta", sa.DateTime(timezone=True), nullable=True),
        sa.Column("eta_approximate", sa.Boolean(), nullable=False),
        sa.Column("arrived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("done_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "event_location",
            geoalchemy2.types.Geography(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeogFromText",
                name="geography",
            ),
            nullable=True,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("operator_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["operator_id"], ["operator.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["request_id"], ["ride_request.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["trip_id"], ["trip.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("trip_id", "sequence", name="uq_trip_stop_sequence"),
    )
    op.create_index(op.f("ix_trip_stop_operator_id"), "trip_stop", ["operator_id"], unique=False)
    op.create_index("ix_trip_stop_request", "trip_stop", ["request_id"], unique=False)
    op.create_index("ix_trip_stop_trip", "trip_stop", ["trip_id", "sequence"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_trip_stop_trip", table_name="trip_stop")
    op.drop_index("ix_trip_stop_request", table_name="trip_stop")
    op.drop_index(op.f("ix_trip_stop_operator_id"), table_name="trip_stop")
    op.drop_table("trip_stop")
    op.drop_index("ix_trip_event_trip", table_name="trip_event")
    op.drop_index(op.f("ix_trip_event_operator_id"), table_name="trip_event")
    op.drop_table("trip_event")
    op.drop_index("ix_trip_vehicle_status", table_name="trip")
    op.drop_index("ix_trip_operator_status", table_name="trip")
    op.drop_index(op.f("ix_trip_operator_id"), table_name="trip")
    op.drop_table("trip")
    # ### end Alembic commands ###
