"""trip_stop eta_updated_at

Revision ID: 69ed4dcdf98d
Revises: f1ad58b98bc8
Create Date: 2026-09-25 10:09:04.511874

"""

from collections.abc import Sequence

import geoalchemy2  # noqa: F401  (geography columns render as geoalchemy2.types.*)
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "69ed4dcdf98d"
down_revision: str | Sequence[str] | None = "f1ad58b98bc8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "trip_stop", sa.Column("eta_updated_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("trip_stop", "eta_updated_at")
    # ### end Alembic commands ###
