"""duty sessions

Revision ID: 30046fc4c016
Revises: 8c89b43d6230
Create Date: 2026-09-24 22:19:20.663028

"""

from collections.abc import Sequence

import geoalchemy2  # noqa: F401  (geography columns render as geoalchemy2.types.*)
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "30046fc4c016"
down_revision: str | Sequence[str] | None = "8c89b43d6230"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "duty_session",
        sa.Column("driver_id", sa.UUID(), nullable=False),
        sa.Column("vehicle_id", sa.UUID(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("mqtt_password_hash", sa.String(length=300), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("operator_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["driver_id"], ["driver.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["operator_id"], ["operator.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["vehicle_id"], ["vehicle.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_duty_session_driver", "duty_session", ["driver_id", "started_at"], unique=False
    )
    op.create_index(
        op.f("ix_duty_session_operator_id"), "duty_session", ["operator_id"], unique=False
    )
    op.create_index(
        "ix_duty_session_vehicle", "duty_session", ["vehicle_id", "started_at"], unique=False
    )
    op.create_index(
        "uq_duty_session_open_driver",
        "duty_session",
        ["driver_id"],
        unique=True,
        postgresql_where="ended_at IS NULL",
    )
    op.create_index(
        "uq_duty_session_open_vehicle",
        "duty_session",
        ["vehicle_id"],
        unique=True,
        postgresql_where="ended_at IS NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_duty_session_open_vehicle",
        table_name="duty_session",
        postgresql_where="ended_at IS NULL",
    )
    op.drop_index(
        "uq_duty_session_open_driver",
        table_name="duty_session",
        postgresql_where="ended_at IS NULL",
    )
    op.drop_index("ix_duty_session_vehicle", table_name="duty_session")
    op.drop_index(op.f("ix_duty_session_operator_id"), table_name="duty_session")
    op.drop_index("ix_duty_session_driver", table_name="duty_session")
    op.drop_table("duty_session")
    # ### end Alembic commands ###
