"""location ping partitioned

Revision ID: 0176544eef99
Revises: 30046fc4c016
Create Date: 2026-09-25 08:44:06.539366

"""

from collections.abc import Sequence

import geoalchemy2  # noqa: F401  (geography columns render as geoalchemy2.types.*)
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "0176544eef99"
down_revision: str | Sequence[str] | None = "30046fc4c016"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "location_ping",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("vehicle_id", sa.UUID(), nullable=False),
        sa.Column("operator_id", sa.UUID(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "location",
            geoalchemy2.types.Geography(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeogFromText",
                name="geography",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("speed_mps", sa.Float(), nullable=True),
        sa.Column("heading_deg", sa.Float(), nullable=True),
        sa.Column("accuracy_m", sa.Float(), nullable=True),
        sa.Column("battery_pct", sa.Integer(), nullable=True),
        sa.Column(
            "source",
            sa.Enum("app", "esp32", "sim", name="gpssource", native_enum=False, length=10),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["vehicle_id"], ["vehicle.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", "recorded_at", name="pk_location_ping"),
        postgresql_partition_by="RANGE (recorded_at)",
    )
    op.create_index(
        "ix_location_ping_operator_time",
        "location_ping",
        ["operator_id", "recorded_at"],
        unique=False,
    )
    op.create_index(
        "ix_location_ping_vehicle_time",
        "location_ping",
        ["vehicle_id", "recorded_at"],
        unique=False,
    )

    # A partitioned table has no storage of its own: without at least one partition every
    # INSERT fails. Create a window of monthly partitions plus a DEFAULT so a ping can
    # never be lost because nobody ran the maintenance job.
    #
    # Monthly rollover and the 90-day drop are an operations job, not a migration; the
    # helpers are in app/modules/tracking/partitions.py.
    op.execute(
        """
        DO $$
        DECLARE
            month_start date := date_trunc('month', now())::date - interval '1 month';
            month_end   date;
            part_name   text;
        BEGIN
            FOR i IN 0..3 LOOP
                month_end := (month_start + interval '1 month')::date;
                part_name := 'location_ping_' || to_char(month_start, 'YYYY_MM');
                EXECUTE format(
                    'CREATE TABLE IF NOT EXISTS %I PARTITION OF location_ping '
                    'FOR VALUES FROM (%L) TO (%L)', part_name, month_start, month_end
                );
                month_start := month_end;
            END LOOP;
        END
        $$;
        """
    )
    op.execute(
        "CREATE TABLE IF NOT EXISTS location_ping_default PARTITION OF location_ping DEFAULT"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_location_ping_vehicle_time", table_name="location_ping")
    op.drop_index("ix_location_ping_operator_time", table_name="location_ping")
    # Dropping the parent drops every partition with it.
    op.drop_table("location_ping")
    # ### end Alembic commands ###
