"""fleet vehicles and drivers

Revision ID: c2b7ff33e90f
Revises: b77d2241c4cb
Create Date: 2026-09-24 21:43:25.291114

"""

from collections.abc import Sequence

import geoalchemy2  # noqa: F401  (geography columns render as geoalchemy2.types.*)
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "c2b7ff33e90f"
down_revision: str | Sequence[str] | None = "b77d2241c4cb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "driver",
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("licence_last4", sa.String(length=4), nullable=True),
        sa.Column("default_vehicle_id", sa.UUID(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("operator_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "licence_last4 IS NULL OR licence_last4 ~ '^[A-Za-z0-9]{4}$'",
            name="ck_driver_licence_last4",
        ),
        sa.ForeignKeyConstraint(["operator_id"], ["operator.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["app_user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("operator_id", "phone", name="uq_driver_operator_phone"),
    )
    op.create_index(op.f("ix_driver_operator_id"), "driver", ["operator_id"], unique=False)
    op.create_index("ix_driver_user", "driver", ["user_id"], unique=False)
    op.create_table(
        "vehicle",
        sa.Column("registration_no", sa.String(length=20), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column(
            "vehicle_type",
            sa.Enum("sedan_4", "suv_6", "vip", name="vehicletype", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("seat_capacity", sa.SmallInteger(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "off_duty",
                "available",
                "on_trip",
                "out_of_service",
                name="vehiclestatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("current_driver_id", sa.UUID(), nullable=True),
        sa.Column("mqtt_username", sa.String(length=100), nullable=True),
        sa.Column(
            "tracker_type",
            sa.Enum("app", "esp32", name="trackertype", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("operator_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "seat_capacity >= 1 AND seat_capacity <= 12", name="ck_vehicle_seat_capacity"
        ),
        sa.ForeignKeyConstraint(["current_driver_id"], ["driver.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["operator_id"], ["operator.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("mqtt_username", name="uq_vehicle_mqtt_username"),
        sa.UniqueConstraint("operator_id", "registration_no", name="uq_vehicle_operator_rego"),
    )
    op.create_index(op.f("ix_vehicle_operator_id"), "vehicle", ["operator_id"], unique=False)
    op.create_index(
        "ix_vehicle_operator_status", "vehicle", ["operator_id", "status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_vehicle_operator_status", table_name="vehicle")
    op.drop_index(op.f("ix_vehicle_operator_id"), table_name="vehicle")
    op.drop_table("vehicle")
    op.drop_index("ix_driver_user", table_name="driver")
    op.drop_index(op.f("ix_driver_operator_id"), table_name="driver")
    op.drop_table("driver")
    # ### end Alembic commands ###
