"""core schema tenancy users roles

Revision ID: 3661eca069ea
Revises:
Create Date: 2026-09-24 21:12:49.256056

"""

from collections.abc import Sequence

import geoalchemy2  # noqa: F401  (geography columns render as geoalchemy2.types.*)
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "3661eca069ea"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_user",
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "suspended", name="userstatus", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("phone ~ '^\\+[1-9][0-9]{7,14}$'", name="ck_app_user_phone_e164"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("phone", name="uq_app_user_phone"),
    )
    op.create_table(
        "operator",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "suspended", name="operatorstatus", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("automation_paused", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "otp_challenge",
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("code_hash", sa.String(length=128), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("attempts >= 0", name="ck_otp_attempts_non_negative"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_otp_challenge_phone", "otp_challenge", ["phone"], unique=False)
    op.create_table(
        "client",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("contact_name", sa.String(length=200), nullable=True),
        sa.Column("contact_phone", sa.String(length=20), nullable=True),
        sa.Column(
            "status",
            sa.Enum("active", "suspended", name="clientstatus", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("operator_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["operator_id"], ["operator.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("operator_id", "name", name="uq_client_operator_name"),
    )
    op.create_index(op.f("ix_client_operator_id"), "client", ["operator_id"], unique=False)
    op.create_table(
        "device",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "platform",
            sa.Enum("android", "ios", "web", name="deviceplatform", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("push_token", sa.String(length=500), nullable=False),
        sa.Column("app_version", sa.String(length=50), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["app_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("push_token", name="uq_device_push_token"),
    )
    op.create_index("ix_device_user", "device", ["user_id"], unique=False)
    op.create_table(
        "refresh_token",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=128), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("device_info", sa.String(length=300), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["app_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash", name="uq_refresh_token_hash"),
    )
    op.create_index("ix_refresh_token_user", "refresh_token", ["user_id"], unique=False)
    op.create_table(
        "zone",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "area",
            geoalchemy2.types.Geography(
                geometry_type="POLYGON",
                srid=4326,
                dimension=2,
                from_text="ST_GeogFromText",
                name="geography",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("operator_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["operator_id"], ["operator.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("operator_id", "name", name="uq_zone_operator_name"),
    )
    op.create_index(op.f("ix_zone_operator_id"), "zone", ["operator_id"], unique=False)
    op.create_table(
        "client_policy",
        sa.Column("client_id", sa.UUID(), nullable=False),
        sa.Column("pooling_allowed", sa.Boolean(), nullable=False),
        sa.Column("employee_opt_out_allowed", sa.Boolean(), nullable=False),
        sa.Column("night_safety_enabled", sa.Boolean(), nullable=False),
        sa.Column("night_start", sa.Time(), nullable=True),
        sa.Column("night_end", sa.Time(), nullable=True),
        sa.Column("max_detour_factor", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("max_detour_minutes", sa.Integer(), nullable=True),
        sa.Column("pickup_window_minutes", sa.Integer(), nullable=True),
        sa.Column("no_show_wait_minutes", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("operator_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "max_detour_factor IS NULL OR (max_detour_factor >= 1.0 AND max_detour_factor <= 3.0)",
            name="ck_client_policy_detour_factor_range",
        ),
        sa.CheckConstraint(
            "max_detour_minutes IS NULL OR (max_detour_minutes >= 0 AND max_detour_minutes <= 60)",
            name="ck_client_policy_detour_minutes_range",
        ),
        sa.CheckConstraint(
            "no_show_wait_minutes IS NULL OR (no_show_wait_minutes >= 1 AND no_show_wait_minutes <= 15)",
            name="ck_client_policy_no_show_range",
        ),
        sa.CheckConstraint(
            "pickup_window_minutes IS NULL OR (pickup_window_minutes >= 0 AND pickup_window_minutes <= 30)",
            name="ck_client_policy_pickup_window_range",
        ),
        sa.ForeignKeyConstraint(["client_id"], ["client.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["operator_id"], ["operator.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("client_id", name="uq_client_policy_client"),
    )
    op.create_index(
        op.f("ix_client_policy_operator_id"), "client_policy", ["operator_id"], unique=False
    )
    op.create_table(
        "office",
        sa.Column("client_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "location",
            geoalchemy2.types.Geography(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeogFromText",
                name="geography",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("address_text", sa.String(length=500), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("operator_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["client_id"], ["client.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["operator_id"], ["operator.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("client_id", "name", name="uq_office_client_name"),
    )
    op.create_index(op.f("ix_office_client_id"), "office", ["client_id"], unique=False)
    op.create_index(op.f("ix_office_operator_id"), "office", ["operator_id"], unique=False)
    op.create_table(
        "user_role",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "platform_admin",
                "operator_admin",
                "supervisor",
                "driver",
                "client_admin",
                "employee",
                name="role",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("operator_id", sa.UUID(), nullable=True),
        sa.Column("client_id", sa.UUID(), nullable=True),
        sa.Column("employee_id", sa.UUID(), nullable=True),
        sa.Column("driver_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(role = 'platform_admin' AND operator_id IS NULL) OR (role <> 'platform_admin' AND operator_id IS NOT NULL)",
            name="ck_user_role_operator_scope",
        ),
        sa.CheckConstraint(
            "(role IN ('client_admin', 'employee') AND client_id IS NOT NULL) OR (role NOT IN ('client_admin', 'employee') AND client_id IS NULL)",
            name="ck_user_role_client_scope",
        ),
        sa.ForeignKeyConstraint(["client_id"], ["client.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["operator_id"], ["operator.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["app_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id",
            "role",
            "operator_id",
            "client_id",
            name="uq_user_role_scope",
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_index(
        "ix_user_role_operator_role", "user_role", ["operator_id", "role"], unique=False
    )
    op.create_index("ix_user_role_user", "user_role", ["user_id"], unique=False)
    op.create_table(
        "employee",
        sa.Column("client_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("office_id", sa.UUID(), nullable=False),
        sa.Column(
            "home_location",
            geoalchemy2.types.Geography(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeogFromText",
                name="geography",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("home_landmark", sa.String(length=300), nullable=True),
        sa.Column("zone_id", sa.UUID(), nullable=True),
        sa.Column("priority", sa.SmallInteger(), nullable=False),
        sa.Column("is_vip", sa.Boolean(), nullable=False),
        sa.Column("night_escort_required", sa.Boolean(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("operator_id", sa.UUID(), nullable=False),
        sa.CheckConstraint("priority >= 1 AND priority <= 10", name="ck_employee_priority_range"),
        sa.ForeignKeyConstraint(["client_id"], ["client.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["office_id"], ["office.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["operator_id"], ["operator.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["app_user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["zone_id"], ["zone.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("client_id", "phone", name="uq_employee_client_phone"),
    )
    op.create_index(
        "ix_employee_operator_client", "employee", ["operator_id", "client_id"], unique=False
    )
    op.create_index(op.f("ix_employee_operator_id"), "employee", ["operator_id"], unique=False)
    op.create_index("ix_employee_user", "employee", ["user_id"], unique=False)
    op.create_table(
        "saved_place",
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.Column(
            "location",
            geoalchemy2.types.Geography(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeogFromText",
                name="geography",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("landmark", sa.String(length=300), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("operator_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["employee_id"], ["employee.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["operator_id"], ["operator.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("employee_id", "label", name="uq_saved_place_employee_label"),
    )
    op.create_index(
        op.f("ix_saved_place_operator_id"), "saved_place", ["operator_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_saved_place_operator_id"), table_name="saved_place")
    op.drop_table("saved_place")
    op.drop_index("ix_employee_user", table_name="employee")
    op.drop_index(op.f("ix_employee_operator_id"), table_name="employee")
    op.drop_index("ix_employee_operator_client", table_name="employee")
    op.drop_table("employee")
    op.drop_index("ix_user_role_user", table_name="user_role")
    op.drop_index("ix_user_role_operator_role", table_name="user_role")
    op.drop_table("user_role")
    op.drop_index(op.f("ix_office_operator_id"), table_name="office")
    op.drop_index(op.f("ix_office_client_id"), table_name="office")
    op.drop_table("office")
    op.drop_index(op.f("ix_client_policy_operator_id"), table_name="client_policy")
    op.drop_table("client_policy")
    op.drop_index(op.f("ix_zone_operator_id"), table_name="zone")
    op.drop_table("zone")
    op.drop_index("ix_refresh_token_user", table_name="refresh_token")
    op.drop_table("refresh_token")
    op.drop_index("ix_device_user", table_name="device")
    op.drop_table("device")
    op.drop_index(op.f("ix_client_operator_id"), table_name="client")
    op.drop_table("client")
    op.drop_index("ix_otp_challenge_phone", table_name="otp_challenge")
    op.drop_table("otp_challenge")
    op.drop_table("operator")
    op.drop_table("app_user")
    # ### end Alembic commands ###
