"""trip_event idempotency key

Revision ID: f1ad58b98bc8
Revises: 8e3b6bba35be
Create Date: 2026-09-25 10:06:51.650016

"""

from collections.abc import Sequence

import geoalchemy2  # noqa: F401  (geography columns render as geoalchemy2.types.*)
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "f1ad58b98bc8"
down_revision: str | Sequence[str] | None = "8e3b6bba35be"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("trip_event", sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("trip_event", sa.Column("client_event_id", sa.UUID(), nullable=True))
    op.create_index("uq_trip_event_client_event", "trip_event", ["client_event_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_trip_event_client_event", table_name="trip_event")
    op.drop_column("trip_event", "client_event_id")
    op.drop_column("trip_event", "occurred_at")
    # ### end Alembic commands ###
