"""operator config and history

Revision ID: b77d2241c4cb
Revises: 3661eca069ea
Create Date: 2026-09-24 21:34:56.914748

"""

from collections.abc import Sequence

import geoalchemy2  # noqa: F401  (geography columns render as geoalchemy2.types.*)
import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b77d2241c4cb"
down_revision: str | Sequence[str] | None = "3661eca069ea"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "operator_config",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("operator_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["operator_id"], ["operator.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["updated_by"], ["app_user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("operator_id", "key", name="uq_operator_config_key"),
    )
    op.create_index(
        op.f("ix_operator_config_operator_id"), "operator_config", ["operator_id"], unique=False
    )
    op.create_table(
        "operator_config_history",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("old_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("new_value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("changed_by", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("operator_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["changed_by"], ["app_user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["operator_id"], ["operator.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_operator_config_history_key",
        "operator_config_history",
        ["operator_id", "key", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_operator_config_history_operator_id"),
        "operator_config_history",
        ["operator_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_operator_config_history_operator_id"), table_name="operator_config_history"
    )
    op.drop_index("ix_operator_config_history_key", table_name="operator_config_history")
    op.drop_table("operator_config_history")
    op.drop_index(op.f("ix_operator_config_operator_id"), table_name="operator_config")
    op.drop_table("operator_config")
    # ### end Alembic commands ###
